//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_PRESTACION_PROFESIONALES
    {
        public int ID_PRESTACION_PROFESIONAL { get; set; }
        public Nullable<int> COD_PRESTACION { get; set; }
        public Nullable<int> COD_PROFESIONAL { get; set; }
        public Nullable<int> CANTIDAD_FIJA_HONORARIO { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public Nullable<System.DateTime> VIGENCIA { get; set; }
    }
}
