//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_HORARIO_PROFESIONAL
    {
        public long ID_HORARIO_PROFESIONAL { get; set; }
        public Nullable<System.DateTime> HORA_INICIO { get; set; }
        public Nullable<System.DateTime> HORA_TERMINO { get; set; }
        public Nullable<System.DateTime> FECHA_DESDE { get; set; }
        public Nullable<System.DateTime> FECHA_HASTA { get; set; }
        public Nullable<int> DURACION_CITA { get; set; }
        public Nullable<int> ESPACIO_ENTRE_CITA { get; set; }
        public Nullable<long> COD_PROFESIONAL { get; set; }
        public int COD_JORNADA { get; set; }
        public Nullable<bool> ATENCION_WEB { get; set; }
    }
}
