//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_TIPO_ORGANIZACION
    {
        public int ID_TIPO_ORGANIZACION { get; set; }
        public string NOMBRE_TIPO { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    }
}
