//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_CONTRATO_ORGANIZACION
    {
        public int ID_CONTRATO_ORGANIZACION { get; set; }
        public Nullable<int> COD_ORGANIZACION { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
        public Nullable<long> COD_PAGO { get; set; }
    }
}
