//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_DETALLE_DIAS_ATENCION
    {
        public long ID_DETALLE_DIA_ATENCION { get; set; }
        public Nullable<int> COD_DIA_SEMANA { get; set; }
        public Nullable<long> COD_HORARIO_PROFESIONAL { get; set; }
        public Nullable<int> COD_BLOQUEO { get; set; }
    }
}
