//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_AJUSTE_DISPONIBILIDAD
    {
        public long ID_AJUSTE_DISPONIBILIDAD { get; set; }
        public Nullable<System.DateTime> HORA_INICIO { get; set; }
        public Nullable<System.DateTime> HORA_TERMINO { get; set; }
        public Nullable<int> COD_DIA_SEMANA { get; set; }
        public Nullable<int> COD_ESTADO { get; set; }
    }
}
