//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGENDAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPS_CONTRATO
    {
        public int ID_CONTRATO { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    }
}
